### ISSUE TITLE
프로젝트 생성 및 .gitignore 추가

### ISSUE THREAD

**Issue by gdtknight** [gdtknight/of-course-refactor#1]
### `Root Project` - `build.gradle`, `settings.gradle`

- [x] `settings.gradle`
```groovy
rootProject.name = 'of-course-refactor'

["comp", "api"].each {

    def compDir = new File(rootDir, it)
    if (!compDir.exists()) {
        compDir.mkdirs()
    }

    def commonGradleFile = new File(compDir, "${it}-common.gradle")
    if (!commonGradleFile.exists()) {
        commonGradleFile.text =
                """

                    apply from: "../build.gradle"
                
                    dependencies {
                
                    }
                    """.stripIndent(20)
    }

    compDir.eachDir { subDir ->

        def gradleFile = new File(subDir.absolutePath, "build.gradle")
        if (!gradleFile.exists()) {
            gradleFile.text =
                    """
                    
                    dependencies {
                
                    }
                
                    """.stripIndent(20)
        }
        [
                "src/main/java/kr/kdtmini5/oc",
                "src/main/resources",
                "src/test/java/kr/kdtmini5/oc",
                "src/test/resources"
        ].each { srcDir ->
            def srcFolder = new File(subDir.absolutePath, srcDir)
            if (!srcFolder.exists()) {
                srcFolder.mkdirs()
            }
        }

        def projectName = ":${it}-${subDir.name}"
        include projectName
        project(projectName).projectDir = subDir
    }
}
```

- [ ] `build.gradle`

```groovy
buildscript {
    ext {
        spring = "2.7.14"
        boot = "org.springframework.boot"
        lombok = "org.projectlombok:lombok"
        sep = File.separator.toString()
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("$boot:spring-boot-gradle-plugin:$spring")
    }
}

allprojects {
    group = "kr.kdtmini5.oc"
    version = "1.0.0"

    repositories {
        mavenCentral()
    }
}

subprojects {

    apply plugin: "java"
    apply plugin: boot
    apply plugin: "io.spring.dependency-management"
    apply plugin: "idea"

    repositories {
        mavenCentral()
    }

    configurations {
        developmentOnly
        runtimeClasspath {
            extendsFrom developmentOnly
        }
    }

    dependencies {
        developmentOnly("$boot:spring-boot-devtools")

        compileOnly lombok
        testCompileOnly lombok
        annotationProcessor lombok
        testAnnotationProcessor lombok

        testImplementation "$boot:spring-boot-starter-test"

        runtimeOnly 'com.h2database:h2'
        runtimeOnly 'com.mysql:mysql-connector-j'
    }

    test {
        useJUnitPlatform()
    }

}

["comp"].each {
    def subProjectDir = new File(projectDir, it)
    subProjectDir.eachDir { dir ->
        def projectName = ":${it}-${dir.name}"
        project(projectName) {
            bootJar.enabled(false)
            jar.enabled(true)
        }
    }
}

["api"].each {
    def subProjectDir = new File(projectDir, it)
    subProjectDir.eachDir { dir ->
        def projectName = ":${it}-${dir.name}"
        project(projectName) {
            bootJar.enabled(true)
            jar.enabled(false)
        }
    }
}

help.enabled(false)
```

## 도커 설정 - 개발용 로컬 DB 설정

```yml
version: '1'

services:
  mysql:
    container_name: of_course_refactor
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3355:${DB_PORT}
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
```

## 모듈 초기화

- [x] `api` -> API 모듈 최상위 디렉토리
  - [x] `staff` -> 스탭 (사용자) API
  - [x] `manager` -> 매니저 (관리자) API
- [x] `comp` -> 공통 라이브러리 모듈 최상위 디렉토리
  - [x] `oc-domain` -> API 에서 사용되는 공통 도메인 모듈
  - [x] `oc-security` -> API 에서 사용되는 공통 인증 모듈
